graph = {
    "admin_block" : ["swadishtam", "creative_zone", "main_ground", "amul", "rajpath"],
    "swadistam" : ["admin_block", "coops", "gym"],
    "coops" : ["swadistam", "gym"],
    "gym": ["swadishtam", "coops"],
    "creative_zone" : ["admin_block", "bb_court","amul", "rajpath"],
    "amul" : ["main_ground", "nlhc", "admin_block", "bb_court", "creative_zone"],
    "main_ground" : ["admin_block", "nlhc", "amul"],
    "bb_court": ["amul","rajpath","creative_zone", "nlhc"],
    "rajpath":["admin_block", "creative_zone","bb_court","main_building"],
    "ccc":["oat","main_building","rajpath","elhc", "nlhc"],
    "oat":["ccc","nlhc","elhc","main_building","it_complex"],
    "elhc":["it_complex", "oat","main_building","ccc"],
    "it_complex":["main_building","elhc","oat","nlhc"],
    "main_building":["rajpath","ccc","oat","elhc", "amphitheatre"],
    "nlhc":["it_complex", "main_ground","amul","bb_court", "oat"],
    "elhc":["it_complex", "oat", "main_building", "nlhc", "ccc"],

    "oat":["elhc", "ccc", "nlhc", "main_building", "rajpath"],
    "aryabhatta":["bhaskara", "chanakya", "rajpath", "main_builing"],
    "bhaskara":["aryabhatta", "chanakya", "main_building", "rajpath"],
    "chanakya":["aryabhatta", "bhaskara", "main_building", "rajpath"],
    "hostel_office":["hostel_a"],
    "amphitheatre":["main_building", "csed","med","eced", "eeed"],
    "csed":["main_building", "amphitheatre","elhc"],
    "eced":["csed","amphitheatre","main_building", "med"],
    "eeed":["med","ced","eced", "csed"],
    "med":["ced","eeed","eced","csed"],
    "ped":["audi"],
    "mtd":[""],
    "arch":["eclhc","sumedhaym", "audi"],
    "chd":["eclhc","sumedhyam","maths","physics"],
    "btd":["chd","sumedhyam","eclhc","maths","physics"],
    "maths":["physics","eclhc","ched","btd", "sumedhyam"],
    "physics":["maths","ched","btd","sumedhyam"],
    "audi":["arch","ped","mech_lab","civil_lab"],
    "mech_lab":["audi","avenue_97","med"],
    "civil_lab":["audi","arch"],
    "production_lab":["audi","civil_lab","ped"],
    "hostel_a":["hostel_office","hostel_b", "mini_canteen"],
    "hostel_b":["hostel_a","hostel_c","mini_canteen"],
    "hostel_c":["mini_canteen","hostel_b","avenue_97"],
    "hostel_d":["hostel_e","hostel_f","mini_canteen","avenue_97"],
    "hostel_e":["hostel_e","mini_canteen","hostel_f","avenue_97"],
    "hostel_f":["hostel_g","mini_canteen","hostel_d","hostel_e","avenue_97"],
    "pg1":["pg2","hostel_a","hostel_b","hostel_c"],
    "pg2":["pg1","hostel_a","hostel_b","hostel_c"],
    "mbh1":["mbh2"],
    "mbh2":["mbh1"],

    "eclhc":["sumedhyam","maths","ched","physics"],
    "sumedhyam":["eclhc","maths","physics","ched"]

}