export const LOCATION_MAP = {
    admin_block: { label: "Admin Block", category: "Central Campus" },
    swadishtam: { label: "Swadishtam", category: "Central Campus" },
    coops: { label: "Cooperative Store", category: "Central Campus" },
    creative_zone: { label: "Creative Zone", category: "Central Campus" },
    main_ground: { label: "Main Ground", category: "Central Campus" },
    main_building: { label: "Main Building", category: "Central Campus" },
    nlhc: { label: "NLHC", category: "Central Campus" },
    elhc: { label: "ELHC", category: "Central Campus" },
    oat: { label: "OAT", category: "Central Campus" },
    rajpath: { label: "Rajpath", category: "Central Campus" },
    bb_court: { label: "Basketball Court", category: "Central Campus" },
    aryabhatta: { label: "Aryabhatta Hall", category: "Central Campus" },
    bhaskara: { label: "Bhaskara Hall", category: "Central Campus" },
    chanakya: { label: "Chanakya Hall", category: "Central Campus" },
    hostel_office: { label: "Hostel Office", category: "Central Campus" },
    amphitheatre: { label: "Amphitheatre", category: "Central Campus" },
    audi: { label: "Auditorium", category: "Central Campus" },
    mini_canteen: { label: "Mini Canteen", category: "Central Campus" },
    avenue_97: { label: "97th Avenue", category: "Central Campus" },

    ccc: { label: "CCC", category: "Labs & Complexes" },
    it_complex: { label: "IT Complex", category: "Labs & Complexes" },
    mech_lab: { label: "Mechanical Eng. Labs", category: "Labs & Complexes" },
    civil_lab: { label: "Civil Eng. Labs", category: "Labs & Complexes" },
    production_lab: { label: "Production Eng. Labs", category: "Labs & Complexes" },

    csed: { label: "CSED", category: "Department Buildings" },
    eced: { label: "ECED", category: "Department Buildings" },
    eeed: { label: "EEE", category: "Department Buildings" },
    med: { label: "Mechanical", category: "Department Buildings" },
    chd: { label: "Chemical", category: "Department Buildings" },
    ced: { label: "Civil", category: "Department Buildings" },
    btd: { label: "Biotechnology", category: "Department Buildings" },
    ped: { label: "Production", category: "Department Buildings" },
    mtd: { label: "Material Science", category: "Department Buildings" },
    egd: { label: "Engineering Physics", category: "Department Buildings" },
    arch: { label: "Architecture", category: "Department Buildings" },
    maths: { label: "Mathematics", category: "Department Buildings" },
    physics: { label: "Physics", category: "Department Buildings" },

    hostel_a: { label: "A Hostel", category: "Hostels" },
    hostel_b: { label: "B Hostel", category: "Hostels" },
    hostel_c: { label: "C Hostel", category: "Hostels" },
    hostel_d: { label: "D Hostel", category: "Hostels" },
    hostel_e: { label: "E Hostel", category: "Hostels" },
    hostel_f: { label: "F Hostel", category: "Hostels" },
    hostel_g: { label: "G Hostel", category: "Hostels" },
    mbh1: { label: "MBH I", category: "Hostels" },
    mbh2: { label: "MBH II", category: "Hostels" },
    lh: { label: "LH", category: "Hostels" },
    mlh: { label: "MLH", category: "Hostels" },
    pg1: { label: "PG Hostel I", category: "Hostels" },
    pg2: { label: "PG Hostel II", category: "Hostels" },

    eclhc: { label: "ECLHC", category: "East Campus" },
    sumedhyam: { label: "Sumedhyam Canteen", category: "East Campus" },

    library: { label: "Central Library", category: "West Campus" },
    guest_house: { label: "Guest House", category: "West Campus" },
    tbi: { label: "TBI", category: "West Campus" },
    swimming_pool: { label: "Swimming Pool", category: "West Campus" },
    bbc: { label: "Bestie Beans Café", category: "West Campus" },
    faculty_residency: { label: "Faculty Residential Area", category: "West Campus" },

    soms: { label: "SOMS", category: "South Campus" },
    mba_auditorium: { label: "MBA Auditorium", category: "South Campus" },
};

export type LocationKey = keyof typeof LOCATION_MAP;